### ISSUE TITLE
Python Program to Find Sum of Natural Numbers Using Recursion

### ISSUE THREAD

**Issue by MryashAditya007** [MryashAditya007/Hacktoberfest2022#11]

**Comment by Mohit-Kukreja-2002** [comment]
is it like a single input say 10 and we need to return 55 as the sum of 1+2+.....+10 
or 
Is it like we have to take 2 numbers in the input?

**Comment by MryashAditya007** [comment]
> is it like a single input say 10 and we need to return 55 as the sum of 1+2+.....+10 or Is it like we have to take 2 numbers in the input?

@Mohit-Kukreja-2002 The first one

**Comment by anirudh0806** [comment]
could you assign this to me?

**Comment by Mohit-Kukreja-2002** [comment]
pls assign me with this

**Comment by Mohit-Kukreja-2002** [comment]
![image](https://user-images.githubusercontent.com/93993902/193592353-43d7171b-f7f6-42c6-8ba2-1fe337a2f44c.png)
 
here is the solution 
I have also sent the pull request please do check.
Thank you :)
